services:
  - type: web
    name: cryo-accem
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: SECURE_COOKIES
        value: "true"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false
      - key: CHARGE_SHEET_CC_EMAIL
        sync: false
      - key: GOOGLE_APPS_SCRIPT_URL
        sync: false
      - key: GOOGLE_APPS_SCRIPT_TOKEN
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPOSITORY
        value: cryo-accem/Cryo-2.0
      - key: GITHUB_BRANCH
        value: main
